### ISSUE TITLE
.AddWorkflowAssociation() for Read Only Content Types throws error

### ISSUE THREAD

**Issue by bradgarner** [SubPointSolutions/spmeta2#1001]
Hello,

As mentioned in a comment on [this ](https://github.com/SubPointSolutions/spmeta2/issues/980)older resolved issue about workflows related to content types I have discovered another issue. Keep in mind that this is something you can do through the UI and that the association does happen.

The following error is thrown when you attempt to .AddWorkflowAssociation() to a content type link model node if the content type is marked as read only as is the case when a content type has been pushed from the content type hub. What is strange is after the error is thrown if I go to the Workflow settings for that Content Type in that library the association was done properly.

Please let me know if you need more information. Thank you.

ModelNode Name:[Contract Initiation and Financial Terms Workflow] WorkflowTemplateName:[Approval - SharePoint 2010] TaskListTitle:[Contract and Agreement Workflow Tasks] HistoryListTitle:[Contract and Agreement Workflow History]

```
Exception was thrown:There was an error while provisioning definition. Check ModelNode prop.
Inner Exception:The content type "Contracts and Agreements Case" at "/sites/cam/contractsandagreements" is read only.

There was an error while provisioning definition. Check ModelNode prop.
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass4_0.<Traverse>b__0(Object childModelHost)
   at SPMeta2.CSOM.ModelHandlers.ListModelHandler.WithResolvingModelHost(ModelHostResolveContext modelHostContext)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass4_0.<Traverse>b__0(Object childModelHost)
   at SPMeta2.CSOM.ModelHandlers.RootWebModelHandler.WithResolvingModelHost(ModelHostResolveContext modelHostContext)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass4_0.<Traverse>b__0(Object childModelHost)
   at SPMeta2.CSOM.ModelHandlers.SiteModelHandler.WithResolvingModelHost(ModelHostResolveContext modelHostContext)
   at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
   at SPMeta2.Services.ModelServiceBase.ProcessModelDeployment(Object modelHost, ModelNode modelNode)
   at SPMeta2.Services.ModelServiceBase.DeployModel(ModelHostBase modelHost, ModelNode model)
   at SPMeta2.CSOM.Services.CSOMProvisionService.DeployModel(ModelHostBase modelHost, ModelNode model)
   at SPMeta2.CSOM.Services.CSOMProvisionServiceExtensions.DeploySiteModel(CSOMProvisionService modelHost, ClientContext context, ModelNode model)
```

**Comment by SubPointSupport** [comment]
Sweet, thanks for 1001 ticket! :)
We'll see what can we do, thanks again for reporting this one.
