### ISSUE TITLE
Module provision fails on the Document library

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#621]
The following model gives an exception:

>>The model looks as follows: 

return SPMeta2Model.NewSiteModel(site => site
.AddWeb(Webs.RootWeb, rootweb => rootweb
.AddHostList(SPMeta2.BuiltInDefinitions.BuiltInListDefinitions.Documents, list => list
.AddModuleFile(Modules.MailTemplate)
)
)
);

I stripped some things to simplify, those shouldn't matter i think. So AddHostList should get me the ootb Documents library so I can add the module file to it, right? The exception returned says; 

{"Deployment fault: Value cannot be null.\r\nParameter name: clientObject in modelnode: Node value: [ListDefinition] - Title: [Documents] Url: [Documents] ContentTypesEnabled:[True] TemplateType:[101] TemplateName:[]"}

Stacktrace:

at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass4.<Traverse>b__2(Object childModelHost)
at SPMeta2.CSOM.ModelHandlers.WebModelHandler.WithResolvingModelHost(ModelHostResolveContext modelHostContext)
at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass4.<Traverse>b__2(Object childModelHost)
at SPMeta2.CSOM.ModelHandlers.SiteModelHandler.WithResolvingModelHost(ModelHostResolveContext modelHostContext)
at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
at SPMeta2.Services.ModelServiceBase.ProcessModelDeployment(Object modelHost, ModelNode modelNode)
at SPMeta2.Services.ModelServiceBase.DeployModel(ModelHostBase modelHost, ModelNode model)
at SPMeta2.CSOM.Services.CSOMProvisionService.DeployModel(ModelHostBase modelHost, ModelNode model)

https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=570358283

**Comment by SubPointSupport** [comment]
Motlikely related to list definition confusion. There are two "Documents" for various web templates. 
SharedDocuments != Documents, the title is the same, but the URL is different.

Below is how BuiltInListDefinitions looks like to address the OOTB lists.

/// <summary>
/// 'Documents' library shortcut.
/// </summary>
public static ListDefinition Documents = new ListDefinition
{
Title = "Documents",
TemplateType = BuiltInListTemplateTypeId.DocumentLibrary,
Url = "Documents",
ContentTypesEnabled = true
};

/// <summary>
/// 'Shared Documents' library shortcut.
/// </summary>
public static ListDefinition SharedDocuments = new ListDefinition
{
Title = "Documents",
TemplateType = BuiltInListTemplateTypeId.DocumentLibrary,
Url = "Shared Documents",
ContentTypesEnabled = true
};

**Comment by SubPointSupport** [comment]
Sorted and confirmed.
