### ISSUE TITLE
AddSecurityRoleLink to Security Group on the site gives error

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#686]
As following:

```
cannot add AddSecurityRoleLink to Security Group. I get following exception:

Cannot resolve role definition for role definition link model:[SecurityRoleName:[Contributor]]

SPMeta2.Exceptions.SPMeta2ModelDeploymentException: There was an error while provisioning definition. Check ModelNode prop. ---> System.ArgumentException: Cannot resolve role definition for role definition link model:[SecurityRoleName:[Contributor]]
at SPMeta2.SSOM.ModelHandlers.SecurityRoleLinkModelHandler.ResolveSecurityRole(SPWeb web, SecurityRoleLinkDefinition rolDefinitionModel)
at SPMeta2.SSOM.ModelHandlers.SecurityRoleLinkModelHandler.ProcessSPGroupHost(SPGroup modelHost, SPGroup securityGroup, SecurityRoleLinkDefinition securityRoleLinkModel)
at SPMeta2.SSOM.ModelHandlers.SecurityRoleLinkModelHandler.DeployModel(Object modelHost, DefinitionBase model)
at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)

This is my code:

List<SecurityGroupDefinition> list = GetDefinitions.GetSecurityGroups();

var model = SPMeta2Model.NewSiteModel(siteModel =>
{
foreach (var item in list)
{
siteModel.AddSecurityGroup(item, sg =>
{
sg.AddSecurityRoleLink(GetDefinitions.GetSecurityRoleLinkDefinitionFromGroup(item.Name));
});
}
});

GetSecurityRoleLinkDefinitionFromGroup returns this:

SecurityRoleLinkDefinition rld = new SecurityRoleLinkDefinition
{
SecurityRoleName = BuiltInSecurityRoleTypes.Contributor
};

It seems like BuiltInSecurityRoleTypes.Contributor is not supported. Custom SecurityRoleDefinition will be added correctly. Am I missing something?
```

https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=594358639

**Comment by SubPointSupport** [comment]
SecurityRoleLinkDefinition allows to define correct role by Name, RoleType and Id. 
There are several pros to address that:

* SecurityRoleLinkDefinition.SecurityRoleName
* SecurityRoleLinkDefinition.SecurityRoleType
* SecurityRoleLinkDefinition.SecurityRoleId

SecurityRoleName goes with the name of the role, BuiltInSecurityRoleNames can be used as a short-cut.

SecurityRoleType should be a type of the role, BuiltInSecurityRoleTypes can be used as a shortcut.

In mentioned case please update BuiltInSecurityRoleTypes.Contributor to BuiltInSecurityRoleNames.Contribute. Typo.

**Comment by SubPointSupport** [comment]
Confirmed, closed.
