### ISSUE TITLE
Content Search Web Part provisioning

### ISSUE THREAD

**Issue by ashuetawah** [SubPointSolutions/spmeta2#894]
I am trying to provision content search web part using XML approach. I have downloaded the xml from site and stored in text/xml file. I am reading file using var content = System.Text.Encoding.UTF8.GetString(ModuleFileUtils.ReadFully(System.IO.File.OpenRead($@"{baseDirectory}\Files\{fileName}"))) and then I consume this in WebPartDefinition.WebpartXmlTemplate property as defined here http://docs.subpointsolutions.com/spmeta2/reference/sp-foundation-definitions/webpartdefinition?#add-web-part-by-xml.
First error as the reading content return \r\n as escape sequence chars, which I removed. Then it keep throwing error as Line 1, Column 1 data is not valid.

**Comment by SubPointSupport** [comment]
We would need the model and the definition so that we can replicate that issues.

**Comment by ashuetawah** [comment]
[HomePage-CompanyNews.txt](https://github.com/SubPointSolutions/spmeta2/files/491655/HomePage-CompanyNews.txt)
I am using attached file for xml definition storage.
using below code to build the web part definition - 
WebPartDefinition CompanyNews
        {
            get
            {
                var contentXML = System.Text.Encoding.UTF8.GetString(ModuleFileUtils.ReadFully(System.IO.File.OpenRead($@"{baseDirectory}\Files\{fileName}")));
contentXML  = contentXML.Replace("\r\n", "");
                return new WebPartDefinition
                {
                    Title = "Company News",
                    Id="CompanyNews_Home",
                    WebpartXmlTemplate = contentXML,//BuiltInWebPartTemplates.ContentBySearchWebPart,
                    ZoneId= "TopLeftRow"
                };
            }
        }
using below code add web part to web page - 
PublishingPageDefinition homePageDefinition = new PublishingPageDefinition
        {
            Title = "Home",
            FileName = "Home.aspx",
            NeedOverride = true,
            PageLayoutFileName = ""Page Layout File Name",
            Values = new List<FieldValue> { new FieldValue { } }
        };
web.AddHostList(BuiltInListDefinitions.Pages, lib =>
{
                lib.AddPublishingPage(homePageDefinition, hp=> 
                {
                    hp.AddWebPart(WebParts.CompanyNews)
                 })
});

**Comment by SubPointSupport** [comment]
Exceptions you have?
CSOM/SSOM?
SharePoint version to provision against?

Does the error happen while provision or while reading XML content to the web part?

**Comment by ashuetawah** [comment]
I can get you the exception details in some time.
CSOM provisioning for SPO.
Error happen when adding web part to page.

**Comment by ashuetawah** [comment]
I tried below 2 steps today 
Step1 = if I pass the builtin contentsearch web part schema, it gets added.
Step2 = if I add that xml schema in .webpart/txt file and then read using System.Text.Encoding.UTF8.GetString(ModuleFileUtils.ReadFully(System.IO.File.OpenRead($@"{baseDirectory}\Files\{fileName}"))); - it return the content with \r\n at end of each line. Which I replace by "". Then add in the webpart xml. It throws the error as below - 
Apologies for delay, but here you go on entire exception - 
SPMeta2.Exceptions.SPMeta2ModelDeploymentException was unhandled
  HResult=-2146232832
  Message=There was an error while provisioning definition. Check ModelNode prop.
  Source=SPMeta2
  StackTrace:
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass4_0.<Traverse>b__0(Object childModelHost)
       at SPMeta2.CSOM.Standard.ModelHandlers.PublishingPageModelHandler.WithResolvingModelHost(ModelHostResolveContext modelHostContext)
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass4_0.<Traverse>b__0(Object childModelHost)
       at SPMeta2.CSOM.ModelHandlers.ListModelHandler.WithResolvingModelHost(ModelHostResolveContext modelHostContext)
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass4_0.<Traverse>b__0(Object childModelHost)
       at SPMeta2.CSOM.ModelHandlers.WebModelHandler.WithResolvingModelHost(ModelHostResolveContext modelHostContext)
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
       at SPMeta2.Services.ModelServiceBase.ProcessModelDeployment(Object modelHost, ModelNode modelNode)
       at SPMeta2.Services.ModelServiceBase.DeployModel(ModelHostBase modelHost, ModelNode model)
       at SPMeta2.CSOM.Services.CSOMProvisionService.DeployModel(ModelHostBase modelHost, ModelNode model)
       at SPMeta2.CSOM.Services.CSOMProvisionServiceExtensions.DeployWebModel(CSOMProvisionService modelHost, ClientContext context, ModelNode model)
       at customer.Intranet.Deploy.Webs.RootWeb.Deploy(ClientContext clientContext, StandardCSOMProvisionService csom) in C:\NCTFS\Intranetv3\source\customer.Intranet\customer.Intranet.Deploy\Webs\RootWeb.cs:line 34
       at customer.Intranet.Deploy.Module.Deploy() in C:\NCTFS\Intranetv3\source\customer.Intranet\customer.Intranet.Deploy\Module.cs:line 28
       at customer.Intranet.Deploy.Program.Main(String[] args) in C:\NCTFS\Intranetv3\source\customer.Intranet\customer.Intranet.Deploy\Program.cs:line 7
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146232000
       LineNumber=1
       LinePosition=1
       Message=Data at the root level is invalid. Line 1, position 1.
       Source=System.Xml
       SourceUri=""
       StackTrace:
            at System.Xml.XmlTextReaderImpl.Throw(Exception e)
            at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
            at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
            at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
            at System.Xml.XmlTextReaderImpl.Read()
            at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
            at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
            at System.Xml.Linq.XDocument.Parse(String text)
            at SPMeta2.Utils.WebpartXmlExtensions.LoadWebpartXmlDocument(String value)
            at SPMeta2.CSOM.ModelHandlers.WebPartModelHandler.ProcessCommonWebpartProperties(String webPartXml, WebPartDefinitionBase definition)
            at SPMeta2.CSOM.ModelHandlers.WebPartModelHandler.<>c__DisplayClass28_1.<DeployModel>b__2(File pageFile)
            at SPMeta2.CSOM.ModelHandlers.ModuleFileModelHandler.WithSafeFileOperation(List list, File file, Func`2 action, Action`1 onCreated, Boolean doesFileHasListItem)
            at SPMeta2.CSOM.ModelHandlers.ModuleFileModelHandler.WithSafeFileOperation(List list, File file, Func`2 action, Boolean doesFileHasListItem)
            at SPMeta2.CSOM.ModelHandlers.WebPartModelHandler.DeployModel(Object modelHost, DefinitionBase model)
            at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
       InnerException:

**Comment by ashuetawah** [comment]
Never mind, I figured it out.
There is something wrong in reading file content (Method - System.Text.Encoding.UTF8.GetString(ModuleFileUtils.ReadFully(System.IO.File.OpenRead($@"{baseDirectory}\Files{fileName}"))); ) . When I replaced with System.IO.File.ReadAllText($@"{baseDirectory}\Files\{fileName}", Encoding.Default); it worked.

**Comment by SubPointSupport** [comment]
Sweet, thanks!

Curiously enough, we use ModuleFileUtils.ReadFully quite intensively in M2 and regression to read binary data. Not sure why default encoding would work differently in your case.

Grad you solved it.
