### ISSUE TITLE
Problem with url in MasterPageSettings

### ISSUE THREAD

**Issue by ReDERO** [SubPointSolutions/spmeta2#936]
### Brief description
We provision site "S1", which is not root site. Our master page located on S1 and we need to activate it.
But when we use scenario from http://docs.subpointsolutions.com/spmeta2/reference/sp-foundation-definitions/masterpagesettingsdefinition?#add-master-page-setting we are getting master page from site collection level. It cause an error for us.
After that we try to use absolute url for our master page. But we get an error while provision, that tell about wrong masterpage URL that contain relative sitecollection URL at the beginning: /sites/test2/https://intelinno.sharepoint.com/sites/test2/departments/it/_catalogs/masterpage/seattle-department.master.

Exception:
SPMeta2.Exceptions.SPMeta2ModelDeploymentException was unhandled
  HResult=-2146232832
  Message=There was an error while provisioning definition. Check ModelNode prop.
  Source=SPMeta2
  StackTrace:
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.<>c__DisplayClass6.<Traverse>b__4(Object childModelHost)
       at SPMeta2.CSOM.ModelHandlers.WebModelHandler.WithResolvingModelHost(ModelHostResolveContext modelHostContext)
       at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
       at SPMeta2.Services.ModelServiceBase.ProcessModelDeployment(Object modelHost, ModelNode modelNode)
       at SPMeta2.Services.ModelServiceBase.DeployModel(ModelHostBase modelHost, ModelNode model)
       at SPMeta2.CSOM.Services.CSOMProvisionService.DeployModel(ModelHostBase modelHost, ModelNode model)
       at SPMeta2.CSOM.Services.CSOMProvisionServiceExtensions.DeployWebModel(CSOMProvisionService modelHost, ClientContext context, ModelNode model)
       at KCSA.Department.Services.PortalStandardCSOMProvisionService.DeployIntranet(ClientContext context, Options options) in C:\Users\abog\Projects\Intranet Portal KMDA\Sources\KCSA\KCSA.Department\Services\PortalStandardCSOMProvisionService.cs:line 56
       at KCSA.Department.Services.PortalStandardCSOMProvisionService.DeployIntranet(ClientContext context) in C:\Users\abog\Projects\Intranet Portal KMDA\Sources\KCSA\KCSA.Department\Services\PortalStandardCSOMProvisionService.cs:line 32
       at KCSA.Department.Program.<>c__DisplayClass0_0.<Main>b__0(ClientContext context) in C:\Users\abog\Projects\Intranet Portal KMDA\Sources\KCSA\KCSA.Department\Program.cs:line 30
       at KCSA.Department.Utils.ConsoleUtils.WithO365Context(String siteUrl, String userName, String userPassword, Action`1 action) in C:\Users\abog\Projects\Intranet Portal KMDA\Sources\KCSA\KCSA.Department\Utils\ConsoleUtilsO365.cs:line 23
       at KCSA.Department.Program.Main(String[] args) in C:\Users\abog\Projects\Intranet Portal KMDA\Sources\KCSA\KCSA.Department\Program.cs:line 21
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233088
       Message=Рядок "/sites/test2/https://intelinno.sharepoint.com/sites/test2/departments/it//_catalogs/masterpage/seattle-department.master" містить неприпустимий символ ":".
       ServerErrorCode=-2146232832
       ServerErrorTraceCorrelationId=09f2c29d-60cf-3000-a357-38370791606b
       ServerErrorTypeName=Microsoft.SharePoint.SPException
       ServerStackTrace=""
       Source=Microsoft.SharePoint.Client.Runtime
       StackTrace:
            at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
            at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
            at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
            at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
            at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
            at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
            at SPMeta2.CSOM.Services.Impl.DefaultClientRuntimeContextService.InternalExecuteQuery(ClientRuntimeContext context)
            at SPMeta2.CSOM.Services.Impl.DefaultClientRuntimeContextService.ExecuteQuery(ClientRuntimeContext context)
            at SPMeta2.CSOM.Extensions.ClientRuntimeContextExtensions.ExecuteQueryWithTrace(ClientRuntimeContext context)
            at SPMeta2.CSOM.ModelHandlers.MasterPageSettingsModelHandler.DeployMasterPageSettings(Object modelHost, WebModelHost webModelHost, MasterPageSettingsDefinition masterPageSettings)
            at SPMeta2.CSOM.ModelHandlers.MasterPageSettingsModelHandler.DeployModel(Object modelHost, DefinitionBase model)
            at SPMeta2.Services.Impl.DefaultModelTreeTraverseService.Traverse(Object modelHost, ModelNode modelNode)
       InnerException: 

### SharePoint API
O365

### SPMeta2 API
SPMeta2.Diagnostic.DiagnosticInfo SPMeta2FileVersion:[1.2.16278.0757]
CSOMFileVersion:[16.1.5715.1200]

### SPMeta2 model
http://docs.subpointsolutions.com/spmeta2/reference/sp-foundation-definitions/masterpagesettingsdefinition?#add-master-page-setting

**Comment by SubPointSupport** [comment]
Bug, for sure. It won't work at the sub-web level as M2 always tries to get the master page from the current web. We'll fix that allowing "~site" and "~sitecollection" tokens to be used in both URL properties within MasterPageSettings 

Will be in the upcoming January update.

**Comment by SubPointSupport** [comment]
Aiming to fix with SPMeta2 1.2.100 release on Feb 6, 2017.

**Comment by SubPointSupport** [comment]
@ReDERO, could you please provide definition and models that cause the trouble? Keen to get on the same page and replicate the issue. Thanks in advance!
